<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 3: Lab Instructions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="03-lab-worksheet_files/libs/clipboard/clipboard.min.js"></script>
<script src="03-lab-worksheet_files/libs/quarto-html/quarto.js"></script>
<script src="03-lab-worksheet_files/libs/quarto-html/popper.min.js"></script>
<script src="03-lab-worksheet_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="03-lab-worksheet_files/libs/quarto-html/anchor.min.js"></script>
<link href="03-lab-worksheet_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="03-lab-worksheet_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="03-lab-worksheet_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="03-lab-worksheet_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="03-lab-worksheet_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 3: Lab Instructions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="purpose" class="level1">
<h1>Purpose</h1>
<p>In today’s lab, we will first discuss how to use R to visualize a correlation, calculate the correlation coefficient, assess statistical significance of the correlation, and report the results.</p>
<p>We will also go over the basics of univariate linear regression in R, including reporting regression results.</p>
<p>For today’s lab, you will need to load the following libraries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych) <span class="co">#for correlation analysis</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(papaja) <span class="co">#for formatting p values</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom) <span class="co">#for formatting tables</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr) <span class="co">#for formatting tables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="to-review" class="level1">
<h1>To review:</h1>
<ul>
<li><p>Correlation is a statistical measure that describes the strength and direction of the relation between two variables.</p></li>
<li><p>Regression is a general approach for data analysis in which a best-fitting linear model (i.e., a line) is used to model the relationship between two variables for which data has been collected: the predictor variable, X, and an outcome variable, Y.</p></li>
<li><p>Regression can handle a variety of types of predictor variables (for example, predictors can be continuous or categorical).</p></li>
<li><p>Today, we’ll just be focusing on univariate linear regression with a single continuous predictor, but over the coming weeks we will build up into much more complicated regression equations.</p></li>
</ul>
</section>
<section id="part-1-correlation" class="level1">
<h1>Part 1: Correlation</h1>
<section id="read-in-the-data" class="level2">
<h2 class="anchored" data-anchor-id="read-in-the-data">Read in the Data</h2>
<p>First, let’s read in the data and then use <code>View()</code> to check it out.</p>
<p>The data file is called <code>consc_health.csv</code>. Please name the data “health”.</p>
<p>The data has 4 columns:</p>
<ul>
<li>pid: an anonymous participant identifier</li>
<li>gender: participant gender</li>
<li>consc: participants’ score on a conscientiousness measure</li>
<li>sr_health: participants’ self-reported health status</li>
</ul>
</section>
<section id="visualizing-correlations" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-correlations">Visualizing correlations</h2>
<p>It is very important to <em>always</em> visualize your data. There might be patterns in your data that are not apparent just from looking at a correlation between two variables. While we will focus on one here, there are many different options for visualizing correlations.</p>
</section>
<section id="scatter-plot" class="level2">
<h2 class="anchored" data-anchor-id="scatter-plot">Scatter plot</h2>
<p>Scatter plots allow us to visualize the relationship between two variables. Let’s create a scatter plot of the relation between conscientiousness and self-reported health using <code>ggplot()</code>.</p>
<blockquote class="blockquote">
<p><strong>Question:</strong> What do you notice about the strength and direction of the data?</p>
</blockquote>
</section>
<section id="calculate-correlation-coefficient-r" class="level2">
<h2 class="anchored" data-anchor-id="calculate-correlation-coefficient-r">Calculate correlation coefficient (<em>r</em>)</h2>
<p>Now, let’s calculate the correlation coefficient for <code>health$consc</code> and <code>health$sr_health</code> using the <code>cor()</code> function (this is in the <code>{stats}</code> package, which is a core package in to R - no need to install/load!).</p>
<blockquote class="blockquote">
<p><strong>Question:</strong> Is the correlation positive or negative? …strong or weak?</p>
</blockquote>
</section>
</section>
<section id="stats" class="level1">
<h1>Hypothesis testing with correlations</h1>
<p>Once you have a correlation coefficient, you may want to assess whether the correlation is statistically meaningful.</p>
<section id="statistical-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="statistical-hypotheses">Statistical hypotheses</h2>
<p><span class="math display">\[\large H_{0}: \rho = 0\]</span></p>
<p><span class="math display">\[\large H_{1}: \rho \neq 0\]</span></p>
</section>
<section id="correlation-test" class="level2">
<h2 class="anchored" data-anchor-id="correlation-test">Correlation test</h2>
<p>You can run a correlation test using the <code>corr.test()</code> function from the <code>{psych}</code> package.</p>
<blockquote class="blockquote">
<p><strong>Question:</strong> What can we conclude about the relationship between conscientiousness and health from this data?</p>
</blockquote>
<p>It is often very useful to save the output of a statistical test to an object that you can then pull useful information out of it.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>A significant positive correlation was found between conscientiousness and self-reported health status, <em>r</em>(58) = 0.48, 95% CI[0.25, 0.65], <em>p</em> &lt; .001.</p>
</section>
</section>
<section id="part-2-regression" class="level1">
<h1>Part 2: Regression</h1>
<p>Let’s add a regression line to the plot we created earlier. You can add a line of best fit by adding a <code>geom_smooth()</code> layer to the plot.</p>
</section>
<section id="estimating-regression-models" class="level1">
<h1>Estimating regression models</h1>
<p>A univariate linear regression model is made up of two parameters: a y-intercept (<span class="math inline">\(\beta_0\)</span>) and a slope (<span class="math inline">\(\beta_1\)</span>). If we had population-level data, we could assess the true value of each of these model terms.</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1X_i + \epsilon_i\]</span></p>
<p>However, because we typically are working with sample data, we most often have to <em>estimate</em> these values in the univariate linear regression model:</p>
<p><span class="math display">\[Y_i = b_0 + b_1X_i + e_i\]</span></p>
<p>We determine the values of these estimates by finding the best-fitting linear model for a set of collected data and determining the slope and y-intercept of the model. Once we have determined our best estimates of the slope and y-intercept for our linear model, we can use these values to calculate fitted values of Y (<span class="math inline">\(\hat{Y_i}\)</span>) given a particular value on our predictor variable, X.</p>
<p><span class="math display">\[\hat{Y_i} = b_0 + b_1X_i\]</span></p>
<blockquote class="blockquote">
<p><strong>Question:</strong> Using the Ordinary Least Squares estimation method, what criteria do we use to determine what is the best-fitting linear model?</p>
</blockquote>
<section id="estimating-a-regression-model-in-r" class="level3">
<h3 class="anchored" data-anchor-id="estimating-a-regression-model-in-r">Estimating a regression model in R</h3>
<p>Let’s go ahead and estimate a regression equation in R.</p>
<p>Conducting regressions in R is actually pretty simple. We use the <code>lm()</code> function, which is part of the pre-loaded <code>{stats}</code> package. The <code>lm()</code> function takes two arguments:</p>
<ol type="1">
<li><p><strong>The formula:</strong> Specify your regression formula in the general form <code>y ~ x</code>.</p></li>
<li><p><strong>The data:</strong> the dataframe that contains the variables in the formula. This is technically optional.</p></li>
</ol>
<p><em>Example:</em> <code>model &lt;- lm(y ~ x, data = df)</code></p>
<p>Let’s perform a linear regression analysis.</p>
<p>Say we’re interested in whether self-reported health scores are related to self-reported conscientiousness scores.</p>
<ul>
<li>Regress self-report health scores on conscientiousness using the <code>lm()</code> function below.</li>
<li>Store the results of <code>lm()</code> in an object called <code>model</code>.</li>
<li>If you’re not sure how to do this, look at the example above!</li>
</ul>
<p>Let’s see what the output looks like.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sr_health ~ consc, data = health)

Coefficients:
(Intercept)        consc  
     1.6570       0.4904  </code></pre>
</div>
</div>
<p>This output provides us with the following:</p>
<ul>
<li><p>The formula we used for the linear model.</p></li>
<li><p>The estimates of the model coefficients, <span class="math inline">\(b_0\)</span> (intercept) and <span class="math inline">\(b_1\)</span> (the slope of conscientiousness).</p></li>
</ul>
<p>We can get even more information using <code>summary()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sr_health ~ consc, data = health)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.5450 -0.6414 -0.1623  0.6817  2.0154 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   1.6570     0.3571   4.641 2.03e-05 ***
consc         0.4904     0.1188   4.128 0.000119 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8854 on 58 degrees of freedom
Multiple R-squared:  0.2271,    Adjusted R-squared:  0.2138 
F-statistic: 17.04 on 1 and 58 DF,  p-value: 0.0001186</code></pre>
</div>
</div>
<p>This output provides us with the following:</p>
<ul>
<li><p>The formula we used for the linear model</p></li>
<li><p>A description of how the residuals are distributed. This is useful for checking whether the normally-distributed residuals assumption has been met. You want a median of approximately 0 and the absolute value of the first quartile (1Q) to be approximately equal to the absolute value of the third quartile (3Q)</p></li>
<li><p>The estimates of the model coefficients (<span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>), the standard error (SE) for each model coefficient estimate, the t-statistic testing the significance of each model coefficient (compared to zero), and the p-value for each t-statistic</p></li>
<li><p>The residual standard error AKA standard error of the estimate</p></li>
<li><p>R-squared (aka the coefficient of determination)</p></li>
<li><p>Adjusted R-squared (R-squared adjusted for number of predictors in the model)</p></li>
<li><p>F-statistic testing the significance of the overall model, along with the <em>p</em>-value corresponding to the F-statistic</p>
<ul>
<li>We’ll talk more about F-statistics next week! For a univariate regression, the F-statistic is the t-value squared (4.128 ^2 = 17.04038).</li>
</ul></li>
</ul>
</section>
<section id="unpacking-the-output" class="level3">
<h3 class="anchored" data-anchor-id="unpacking-the-output">Unpacking the output</h3>
<p>Let’s unpack some of that output. First, let’s start with understanding how the two measures of overall model fit, <em>residual standard error</em> and <em>r-squared</em>, are being derived.</p>
<section id="residual-standard-error" class="level4">
<h4 class="anchored" data-anchor-id="residual-standard-error">Residual standard error</h4>
<p>The <strong>residual standard error</strong>, also called the <strong>standard error of the estimate</strong>, measures the average deviation between observed and fitted values of Y. It is in the original units of the outcome variable, Y. See the formula below.</p>
<p><span class="math display">\[\sqrt{\frac{\Sigma(Y_i - \hat{Y_i})^2}{N-2}}\]</span></p>
<p>Let’s calculate the residual standard error from scratch, and then I will show you how to pull this value directly from the output.</p>
<p>First, we need to get the predicted values of Y.</p>
<p>Our regression model object, called <code>model</code>, is actually a <code>list</code> that contains a lot of useful information that we don’t see in the output above. Let’s take a look at all the information stored in this object using the <code>str()</code> function.</p>
<p>We can extract elements from this list by using <code>LIST$ELEMENT</code> or <code>LIST[["ELEMENT"]]</code>.</p>
</section>
</section>
<section id="extracting-predicted-y-values" class="level3">
<h3 class="anchored" data-anchor-id="extracting-predicted-y-values">Extracting predicted Y values</h3>
<p>The fitted values of Y are stored in <code>model</code> in an element called <code>fitted.values</code>. Using the instructions about how to extract elements from lists right above, extract the fitted values from the model and store these in an object called <code>fitted_y</code>. Print <code>fitted_y</code>.</p>
<p>Next, calculate the difference between the actual values of Y and the fitted values of Y. Store the output in an object called <code>residuals</code> and print them.</p>
</section>
<section id="extracting-residuals" class="level3">
<h3 class="anchored" data-anchor-id="extracting-residuals">Extracting residuals</h3>
<p>OK, so I made you do extra work. You can actually grab the residuals directly from the <code>model</code> object using <code>model$residuals</code>.</p>
<p>Let’s check to see that our calculation of the residuals matches what we grabbed directly from the model output.</p>
<section id="sum-of-squared-residuals" class="level4">
<h4 class="anchored" data-anchor-id="sum-of-squared-residuals">Sum of squared residuals</h4>
<p>With this information, we could calculate the sum of squared residuals, which is the numerator of the residual standard error equation:</p>
<p><span class="math display">\[\Sigma(Y_i - \hat{Y_i})^2\]</span></p>
<p>Calculate the sum of squared residuals and store the output in an object called <code>sum_sq_residuals</code>.</p>
<p>Finally, now that we have pulled the necessary components, calculate the residual standard error using the formula above. Store the results of the calculation to an object called <code>residual_standard_error</code>.</p>
</section>
</section>
<section id="extracting-residual-standard-error" class="level3">
<h3 class="anchored" data-anchor-id="extracting-residual-standard-error">Extracting residual standard error</h3>
<p>We can also get the standard error more directly. However, it is not stored in the model object that we stored the output of the <code>lm()</code> function to. It is stored in the output of the <code>summary()</code> function. Let’s assign the output of this function to an object called <code>model_summary</code>, and then inspect its structure.</p>
<p>Can you find what the residual standard error is called? Once you find it, extract it from the model_summary.</p>
<p>Is it equivalent to what we calculated above?</p>
<blockquote class="blockquote">
<p><strong>Question:</strong> What does this residual standard error (AKA standard error of the estimate) mean?</p>
</blockquote>
</section>
<section id="the-coefficient-of-determination-r2" class="level3">
<h3 class="anchored" data-anchor-id="the-coefficient-of-determination-r2">The coefficient of determination (<span class="math inline">\(R^2\)</span>)</h3>
<section id="calculating-r2-by-hand" class="level4">
<h4 class="anchored" data-anchor-id="calculating-r2-by-hand">Calculating <span class="math inline">\(R^2\)</span> ‘by hand’</h4>
<p>Another measure of how well our linear model is capturing variation in the outcome variable is <span class="math inline">\(R^2\)</span>.</p>
<p>Let’s calculate <span class="math inline">\(R^2\)</span> by hand first. Here is the formula:</p>
<p><span class="math display">\[R^2 = \frac{SS_{Model}}{SS_{Total}} = \frac{\Sigma(\hat{Y_i} - \bar{Y})^2}{\Sigma(Y_i - \bar{Y})^2}\]</span></p>
<p>Calculate the following:</p>
<ul>
<li><p><span class="math inline">\(SS_{Model}\)</span></p></li>
<li><p><span class="math inline">\(SS_{Total}\)</span></p></li>
<li><p><span class="math inline">\(R^2\)</span></p></li>
</ul>
</section>
<section id="extracting-r2" class="level4">
<h4 class="anchored" data-anchor-id="extracting-r2">Extracting <span class="math inline">\(R^2\)</span></h4>
<p>The coefficient of determination is also stored in the element called <code>r.squared</code>. This represents the proportion of variance explained by the model. Like the residual standard error, we need to use the summary function to get it:</p>
<p>Is it equivalent to what we calculated above?</p>
<blockquote class="blockquote">
<p><strong>Question:</strong> What does this r-squared value mean (in plain English)?</p>
</blockquote>
</section>
</section>
<section id="regression-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="regression-coefficients">Regression coefficients</h3>
<p>We also get estimates for the individual regression coefficients, <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> in the case of univariate regression.</p>
<section id="calculating-regression-coefficients-by-hand" class="level4">
<h4 class="anchored" data-anchor-id="calculating-regression-coefficients-by-hand">Calculating regression coefficients ‘by hand’</h4>
<p>We can calculate these from scratch using the following formulas.</p>
<p>For obtaining <span class="math inline">\(b_1\)</span>:</p>
<p><span class="math display">\[b_1 = r(\frac{s_y}{s_x})\]</span></p>
<p>Calculate <span class="math inline">\(b_1\)</span> using the equation above. Store the value in an object called <code>b1</code>.</p>
<p>And for obtaining <span class="math inline">\(b_0\)</span>:</p>
<p><span class="math display">\[b_0 = M_y - b_1M_x\]</span></p>
<p>Calculate <span class="math inline">\(b_0\)</span> using the equation above. Store the value in an object called <code>b0</code>.</p>
</section>
<section id="extracting-regression-coefficients" class="level4">
<h4 class="anchored" data-anchor-id="extracting-regression-coefficients">Extracting regression coefficients</h4>
<p>We can also grab these estimates from the model output using <code>model$coefficients</code> or the <code>coef()</code> function.</p>
<blockquote class="blockquote">
<p><strong>Question:</strong> What does the intercept mean?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Question:</strong> What about the slope for conscientiousness?</p>
</blockquote>
<p>We can get the confidence intervals around those coefficients by using the <code>confint</code> function from the <code>{stats}</code> package.</p>
</section>
<section id="getting-standardized-coefficients" class="level4">
<h4 class="anchored" data-anchor-id="getting-standardized-coefficients">Getting standardized coefficients</h4>
<p>These are called the <em>unstandardized</em> coefficients. We can also get the standardized coefficients. Standardized regression coefficients, often notated as <span class="math inline">\(\beta\)</span>, are just the regression coefficients after the variables have been <em>standardized</em> or <em>Z-scored</em>. To obtain them, we need to z-score our data with <code>scale()</code> before we run the <code>lm()</code> function. One really cool thing is that we can do it in the <code>lm()</code> call:</p>
<blockquote class="blockquote">
<p><strong>Question:</strong> What does the standardized slope for conscientiousness mean?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Question:</strong> Why is the intercept zero?</p>
</blockquote>
</section>
<section id="getting-the-p-values" class="level4">
<h4 class="anchored" data-anchor-id="getting-the-p-values">Getting the p-values</h4>
<p>We can also test the significance of each of the regression coefficient estimates.</p>
<p>Recall that for each coefficient, we get a <em>t</em>-test from the formula:</p>
<p><span class="math display">\[t = \frac{b_1}{se_b}\]</span></p>
<p>Where the standard error is:</p>
<p><span class="math display">\[se_b = \frac{s_Y}{s_X}\sqrt{\frac{1 - r^2_{XY}}{n-2}}\]</span></p>
<p>(note: the equation above uses slightly different notation than we used in class, but it produces the same result)</p>
<p>This <em>t</em> is distributed with <span class="math inline">\(df = n - 2\)</span> (or <span class="math inline">\(df = n - k - 1\)</span>).</p>
<p>We can get these from the summary of our model object by extracting the coefficients from the summary.</p>
<p>As an aside, let’s take a look at the correlation value that we calculated earlier. What do you notice?</p>
<blockquote class="blockquote">
<p><strong>Question:</strong> Is the test of the intercept significant? What does this mean?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Question:</strong> Is the test of the slope significant? What does this mean?</p>
</blockquote>
</section>
</section>
</section>
<section id="a-tidier-way-to-extract-information" class="level1">
<h1>A tidier way to extract information</h1>
<p>You may have noticed at this point that working with lists has its challenges. Even just extracting the information we’ve extracted so far has some pretty messy code. There must be a better (tidier) way!</p>
<p>Thankfully, there is. The <code>{broom}</code> package is a package for <em>tidying</em> the results of models. It’s pretty easy to use—you just pass the model object to a function from <code>{broom}</code> called <code>tidy()</code>. There are some more advanced things you can do, but just <code>tidy(model)</code> works for most purposes. And one really nice thing about <code>{broom}</code> is that it works with a lot of different types of models, so this will continue to work as we move to other techniques (e.g., multi-level modelling with <code>{lme4}</code>).</p>
<section id="tidy" class="level3">
<h3 class="anchored" data-anchor-id="tidy"><code>tidy()</code></h3>
<p>Let’s see what happens when we tidy our model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    1.66      0.357      4.64 0.0000203
2 consc          0.490     0.119      4.13 0.000119 </code></pre>
</div>
</div>
<p>You can see it produces a dataframe containing the model coefficients and their significance tests. If you also want to get the confidence intervals around those coefficients, you simply need to add the argument <code>conf.int = TRUE</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    1.66      0.357      4.64 0.0000203    0.942     2.37 
2 consc          0.490     0.119      4.13 0.000119     0.253     0.728</code></pre>
</div>
</div>
</section>
</section>
<section id="reporting-regressions" class="level1">
<h1>Reporting regressions</h1>
<p>The last thing we’ll cover today is how to report the results of your regression in Tables.</p>
<section id="create-tables-using-broom-and-kable" class="level3">
<h3 class="anchored" data-anchor-id="create-tables-using-broom-and-kable">Create tables using <code>{broom}</code> and <code>{kable}</code></h3>
<p>Our first option would be to make a table ‘by hand’ using a combination of <code>tidy()</code> and the <code>kable()</code> function from <code>{knitr}</code>.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Results of Regressing Self-Reported Health on Conscientiousness</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.66</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">4.64</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">consc</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">4.13</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We could clean things up a bit more by changing the names and reformatting that pesky p-value column:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Results of Regressing Self-Reported Health on Conscientiousness</caption>
<thead>
<tr class="header">
<th style="text-align: left;">coefficient</th>
<th style="text-align: right;">b</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">t</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.66</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">4.64</td>
<td style="text-align: left;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">consc</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">4.13</td>
<td style="text-align: left;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This method is nice for two reasons:</p>
<ol type="1">
<li><p>You have a lot of control over how things look.</p></li>
<li><p>It’s pretty general-purpose, and you can easily adapt it to new things you learn how to do in R.</p></li>
</ol>
<p>However, it has a downside in that it is hard to get this into picture perfect APA format (we didn’t get all the way there above) and so you may have to do some editing once you get it into word.</p>
</section>
<section id="make-sure-to-always-include-a-written-summary" class="level2">
<h2 class="anchored" data-anchor-id="make-sure-to-always-include-a-written-summary">Make sure to always include a written summary!</h2>
<p>You might want to save the relevant pieces as objects first.</p>
<p>We conducted a univariate linear regression to examine the relation between conscientiousness and self-reported health. Overall, our model that included conscientiousness explained 23% of the variance in self-reported health. We found a positive relation such that individuals who had higher conscientiousness scores also reported better health, <span class="math inline">\(\beta\)</span> = 0.36, 95% CI[0.25, 0.73], <em>t</em> = 4.13, <em>p</em> &lt; .001.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>