<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 6: Lab Starter - KEY</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="06-lab-starter-key_files/libs/clipboard/clipboard.min.js"></script>
<script src="06-lab-starter-key_files/libs/quarto-html/quarto.js"></script>
<script src="06-lab-starter-key_files/libs/quarto-html/popper.min.js"></script>
<script src="06-lab-starter-key_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="06-lab-starter-key_files/libs/quarto-html/anchor.min.js"></script>
<link href="06-lab-starter-key_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="06-lab-starter-key_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="06-lab-starter-key_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="06-lab-starter-key_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="06-lab-starter-key_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 6: Lab Starter - KEY</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="purpose" class="level1">
<h1>Purpose</h1>
<p>In today’s lab, we will practice calculating effect sizes and estimating power using different methods.</p>
<p>For today’s lab, you will need to load the following libraries (lots of them today!).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.5.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(papaja) <span class="co">#for formatting p values</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans) <span class="co">#for post-hoc t-tests</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr) <span class="co">#for formatting tables</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrain) <span class="co">#for creating raincloud plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggrain' was built under R version 4.5.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MOTE) <span class="co">#for getting ci around effect sizes</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'MOTE' was built under R version 4.5.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WebPower) <span class="co">#for calculating power</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lavaan' was built under R version 4.5.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Superpower) <span class="co">#for simulating power</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="research-scenario" class="level1">
<h1>Research scenario</h1>
<p>In today’s lab, we will be using data from <a href="https://link.springer.com/article/10.1007/s11409-021-09260-0">Tekin et al., 2021</a>; Experiment 1. In their study, participants viewed cue-target pairs (e.g., DOOR - HOUSE) during a study phase. After, groups either provided delayed judgments of learning (JOLs; e.g., given a cue word, how likely is it on a scale of 0-100 you will recall the target on a later test), attempted to retrieve the target word (DOOR-?), or restudied the same cue-target pairs (DOOR-HOUSE). Each group then took a final test over the pairs. The aim of their study was to determine whether engaging in retrieval practice or providing delayed JOLs had similar effects on memory.</p>
<section id="read-in-the-data" class="level2">
<h2 class="anchored" data-anchor-id="read-in-the-data">Read in the data</h2>
<p>First, let’s read in the data and then use <code>View()</code> to check it out.</p>
<p>Today’s dataset is called <code>cue_data.csv</code>. Let’s read it in and name it <code>cue_data</code>.</p>
<p>The data has 3 columns:</p>
<ul>
<li>Participant: a numeric indicator of participant number</li>
<li>Total_Final: scores on the final test (percent correct)</li>
<li>Condition: delayed judgment (<code>Cue-only JOL</code>), retrieval (<code>Overt retrie</code>), or restudy the same pairs (<code>Restudy</code>) - there is also a condition called <code>Cue-target J</code> that we are not using.</li>
</ul>
</section>
</section>
<section id="effect-size" class="level1">
<h1>Effect size</h1>
<p>We are interested in the scores on the final test (<code>Total Final)</code> as a function of Condition (<code>Condition</code>). We will only be looking at three conditions: <code>Restudy</code>, <code>Overt retrieval</code> (retrieval practice), and <code>Cue-Only JOL</code>.</p>
<p>First, we will filter the data to remove <code>Cue-target J</code> from the <code>Condition</code> column.</p>
<section id="examine-data." class="level2">
<h2 class="anchored" data-anchor-id="examine-data.">Examine data.</h2>
<p>Let’s take a look at the data, what changes might you want to make?</p>
<p>Visualize the differences between the three groups.</p>
<p>The visualization we are using is called a raincloud plot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-lab-starter-key_files/figure-html/visualization-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Run a model using <code>lm()</code> predicting Total_Final from Condition. Get a summary of your model.</p>
<p>What is your interpretation of each of the predictors? What does the F value tell you? What is the overall effect size?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Total_Final ~ Condition, data = cue_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.38000 -0.10700 -0.02450  0.09425  0.40000 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            0.50000    0.02413  20.719   &lt;2e-16 ***
ConditionOvert retrie  0.02450    0.03476   0.705   0.4823    
ConditionRestudy      -0.06300    0.03476  -1.812   0.0724 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1582 on 120 degrees of freedom
Multiple R-squared:  0.0516,    Adjusted R-squared:  0.03579 
F-statistic: 3.264 on 2 and 120 DF,  p-value: 0.04164</code></pre>
</div>
</div>
<p>Maybe instead we want all possible comparisons. One option is to change the reference level and run another regression. Another option is to use <code>emmeans</code>.</p>
<p>Use <code>emmeans</code> to get all pairwise comparisons. Apply a bonferroni adjustment.</p>
<p>Interpret your comparisons. How do these comparisons differ (or not) from your model summary above?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>pairs <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model, pairwise <span class="sc">~</span> Condition, <span class="at">adjust =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Look what happens if we don't adjust for multiple comparisons (compare this to your summary)</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(model, pairwise <span class="sc">~</span> Condition, <span class="at">adjust =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 Condition    emmean     SE  df lower.CL upper.CL
 Cue-only JOL  0.500 0.0241 120    0.452    0.548
 Overt retrie  0.524 0.0250 120    0.475    0.574
 Restudy       0.437 0.0250 120    0.387    0.487

Confidence level used: 0.95 

$contrasts
 contrast                      estimate     SE  df t.ratio p.value
 (Cue-only JOL) - Overt retrie  -0.0245 0.0348 120  -0.705  0.4823
 (Cue-only JOL) - Restudy        0.0630 0.0348 120   1.812  0.0724
 Overt retrie - Restudy          0.0875 0.0354 120   2.473  0.0148</code></pre>
</div>
</div>
<p>Calculate Cohen’s d “by hand” for each of the pairwise comparisons.</p>
<p>Cohen’s d: <span class="math inline">\(d = \frac{\overline{X}_1 - \overline{X}_2}{S_p}\)</span></p>
<p>Pooled SD (equal ns): <span class="math inline">\(S_p = \sqrt{\frac{(S_1^2 + S_2^2)}{2}}\)</span></p>
<p>Pooled SD (unequal ns): <span class="math inline">\(S_p = \sqrt{\frac{(n_1 - 1)S_1^2 + (n_2 - 1)S_2^2}{n_1 + n_2 - 2}}\)</span></p>
<p>First get means, standard deviations and ns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first, get means, sds, and ns</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>cue_data <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Condition)<span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(Total_Final), <span class="at">sd=</span><span class="fu">sd</span>(Total_Final), <span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Condition     mean    sd     n
  &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1 Cue-only JOL 0.5   0.168    43
2 Overt retrie 0.524 0.135    40
3 Restudy      0.437 0.169    40</code></pre>
</div>
</div>
<p>Which equation for SD should we use?</p>
<p>Note: our Pooled SD will differ based on the comparison we’re testing.</p>
<p>Calculate Cohen’s d for each paired comparison.</p>
<p>Take a look at your effect sizes. Are they small, medium, or large?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># students: fill in these equations</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># cue_overt &lt;- XXX</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># cue_restudy &lt;- XXX</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># overt_restudy &lt;- XXX</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># cue_overt</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># cue_restudy</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co"># overt_restudy</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>cue_overt <span class="ot">&lt;-</span> (.<span class="dv">500</span><span class="fl">-.524</span>)<span class="sc">/</span> <span class="fu">sqrt</span>( ((<span class="dv">43</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">0.168</span> <span class="sc">^</span> <span class="dv">2</span> <span class="sc">+</span> (<span class="dv">40</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> .<span class="dv">135</span> <span class="sc">^</span> <span class="dv">2</span>) <span class="sc">/</span> (<span class="dv">43</span> <span class="sc">+</span> <span class="dv">40</span> <span class="sc">-</span> <span class="dv">2</span>))</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>cue_restudy <span class="ot">&lt;-</span> (.<span class="dv">500</span><span class="fl">-.437</span>)<span class="sc">/</span> <span class="fu">sqrt</span>( ((<span class="dv">43</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">0.168</span> <span class="sc">^</span> <span class="dv">2</span> <span class="sc">+</span> (<span class="dv">40</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> .<span class="dv">169</span> <span class="sc">^</span> <span class="dv">2</span>) <span class="sc">/</span> (<span class="dv">43</span> <span class="sc">+</span> <span class="dv">40</span> <span class="sc">-</span> <span class="dv">2</span>))</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>overt_restudy <span class="ot">&lt;-</span> (.<span class="dv">524</span><span class="fl">-.437</span>)<span class="sc">/</span> <span class="fu">sqrt</span>((<span class="fl">0.135</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> .<span class="dv">169</span><span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>cue_overt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1568605</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>cue_restudy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3739267</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>overt_restudy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5688219</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Heuristics for Cohen's d: 0.20 = S, 0.50 = M, 0.80 = L</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There is an easier way!</p>
<p>We can also use the <code>MOTE</code> package to get an estimate of our effect size and a confidence interval around our effect size.</p>
<p>Let’s first check out the <code>d_ind_t</code> function. What information do you need to provide?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>?d_ind_t</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># students: fill in arguments</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># cue_overt_d &lt;- d_ind_t(XXX)</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># cue_restudy_d &lt;- d_ind_t(XXX)</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co">#                     </span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># overt_restudy_d &lt;- d_ind_t(XXX)</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>cue_overt_d <span class="ot">&lt;-</span> <span class="fu">d_ind_t</span>(<span class="at">m1 =</span> .<span class="dv">500</span>, <span class="at">m2 =</span> .<span class="dv">524</span>, .<span class="dv">168</span>, .<span class="dv">135</span>, <span class="dv">43</span>, <span class="dv">40</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>cue_restudy_d <span class="ot">&lt;-</span> <span class="fu">d_ind_t</span>(.<span class="dv">500</span>, .<span class="dv">437</span>, .<span class="dv">168</span>, .<span class="dv">169</span>, <span class="dv">43</span>, <span class="dv">40</span>)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>                    </span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>overt_restudy_d <span class="ot">&lt;-</span> <span class="fu">d_ind_t</span>(.<span class="dv">524</span>, .<span class="dv">437</span>, .<span class="dv">135</span>, .<span class="dv">169</span>, <span class="dv">40</span>, <span class="dv">40</span>)</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>cue_overt_d<span class="sc">$</span>estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "$d_s$ = -0.16, 95\\% CI [-0.59, 0.27]"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>cue_restudy_d<span class="sc">$</span>estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "$d_s$ = 0.37, 95\\% CI [-0.06, 0.81]"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>overt_restudy_d<span class="sc">$</span>estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "$d_s$ = 0.57, 95\\% CI [0.12, 1.01]"</code></pre>
</div>
</div>
<p>Compare these to the Cohen’s d values that you calculated “by hand.” How do they compare?</p>
<p>Now, write an APA style summary of your results. This should include information about your overall model (e.g., <em>F</em> and <em>R</em><sup>2</sup>) as well as each of the pairwise comparisons and all relevant information (<em>t</em>, <em>p</em>, effect size, 95% CIs). Make sure you have corrected for pairwise comparisons and state which correction you used.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First, let's get all of the objects we will need. You can also do some of this within your summary, but I like to lay it all out here.</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>mod_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>aov_model <span class="ot">&lt;-</span> <span class="fu">anova</span>(model)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co">#descriptives</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>descriptives <span class="ot">&lt;-</span> cue_data <span class="sc">%&gt;%</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Condition)<span class="sc">%&gt;%</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(Total_Final), <span class="at">sd=</span><span class="fu">sd</span>(Total_Final), <span class="at">n=</span><span class="fu">n</span>())</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>cue_mean <span class="ot">&lt;-</span> <span class="fu">round</span>(descriptives<span class="sc">$</span>mean[<span class="dv">1</span>], <span class="dv">2</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>cue_sd <span class="ot">&lt;-</span> <span class="fu">round</span>(descriptives<span class="sc">$</span>sd[<span class="dv">1</span>], <span class="dv">2</span>)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>overt_mean <span class="ot">&lt;-</span> <span class="fu">round</span>(descriptives<span class="sc">$</span>mean[<span class="dv">2</span>], <span class="dv">2</span>)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>overt_sd <span class="ot">&lt;-</span> <span class="fu">round</span>(descriptives<span class="sc">$</span>sd[<span class="dv">2</span>], <span class="dv">2</span>)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>restudy_mean <span class="ot">&lt;-</span> <span class="fu">round</span>(descriptives<span class="sc">$</span>mean[<span class="dv">3</span>], <span class="dv">2</span>)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>restudy_sd <span class="ot">&lt;-</span> <span class="fu">round</span>(descriptives<span class="sc">$</span>sd[<span class="dv">3</span>], <span class="dv">2</span>)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="co">#omnibus effects</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>aov_df_1 <span class="ot">&lt;-</span> aov_model<span class="sc">$</span>Df[<span class="dv">1</span>]</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>aov_df_2 <span class="ot">&lt;-</span> aov_model<span class="sc">$</span>Df[<span class="dv">2</span>]</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>aov_f_val <span class="ot">&lt;-</span> <span class="fu">round</span>(aov_model<span class="sc">$</span>F[<span class="dv">1</span>], <span class="dv">2</span>)</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>aov_p_val <span class="ot">&lt;-</span> aov_model<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>]</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> <span class="fu">round</span>(mod_summary<span class="sc">$</span>r.squared, <span class="dv">2</span>)</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>adj_r_squared <span class="ot">&lt;-</span> <span class="fu">round</span>(mod_summary<span class="sc">$</span>adj.r.squared, <span class="dv">2</span>)</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="co">#get df for contrasts</span></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>contrast_df <span class="ot">&lt;-</span> <span class="fu">summary</span>(pairs)<span class="sc">$</span>contrasts<span class="sc">$</span>df[<span class="dv">1</span>]</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a><span class="co">#Cue v. Overt (note: use t and p values from emmeans because it has the correction!)</span></span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a>cvo_tval <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(pairs)<span class="sc">$</span>contrasts<span class="sc">$</span>t[<span class="dv">1</span>], <span class="dv">2</span>)</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>cvo_pval <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(pairs)<span class="sc">$</span>contrasts<span class="sc">$</span>p.value[<span class="dv">1</span>], <span class="dv">2</span>)</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>cvo_d <span class="ot">&lt;-</span> cue_overt_d<span class="sc">$</span>estimate</span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a><span class="co">#Cue v. Restudy (note: use t and p values from emmeans because it has the correction!)</span></span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a>cvr_tval <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(pairs)<span class="sc">$</span>contrasts<span class="sc">$</span>t[<span class="dv">2</span>], <span class="dv">2</span>)</span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a>cvr_pval <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(pairs)<span class="sc">$</span>contrasts<span class="sc">$</span>p.value[<span class="dv">2</span>], <span class="dv">2</span>)</span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a>cvr_d <span class="ot">&lt;-</span> cue_restudy_d<span class="sc">$</span>estimate</span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a><span class="co">#Overt v. Restudy (note: use t and p values from emmeans because it has the correction!)</span></span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a>ovr_tval <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(pairs)<span class="sc">$</span>contrasts<span class="sc">$</span>t[<span class="dv">3</span>], <span class="dv">2</span>)</span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a>ovr_pval <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(pairs)<span class="sc">$</span>contrasts<span class="sc">$</span>p.value[<span class="dv">3</span>], <span class="dv">2</span>)</span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a>ovr_d <span class="ot">&lt;-</span> overt_restudy_d<span class="sc">$</span>estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="review-the-summary-notice-all-of-the-different-pieces-that-are-present" class="level2">
<h2 class="anchored" data-anchor-id="review-the-summary-notice-all-of-the-different-pieces-that-are-present">Review the summary – notice all of the different pieces that are present!</h2>
<p>We ran a linear regression to examine the effect of delayed judgments of learning (JOLs), retrieval practice, and overt retries on memory. An omibus test revealed a significant effect of condition on memory, F(2, 120) = 3.26, <em>p</em> .042). The model explained a small proportion of variance in memory, with an R<sup>2</sup> = 0.05 and an adjusted R<sup>2</sup> = 0.04. To find the source of this effect, we computed pairwise comparisons for each of our conditions. Participants’ memory in the delayed judgment condition (<em>M</em> = 0.5, SD 0.17) did not differ significantly from participants’ memory in the overt retrieval condition (<em>M</em> = 0.52, SD 0.14), <span class="math inline">\(t(120) = -0.7, p &gt; .999\)</span>, <span class="math inline">\(d_s\)</span> = -0.16, 95% CI [-0.59, 0.27], nor did it differ from participants’ memory in the restudy condition (<em>M</em> = 0.44, SD 0.17), <span class="math inline">\(t(120) = 1.81, p = .220\)</span>, <span class="math inline">\(d_s\)</span> = 0.37, 95% CI [-0.06, 0.81]. However, participants in the overt retrieval condition had significantly greater memory scores than participants in the restudy condition (<em>M</em> = 0.44, SD 0.17), <span class="math inline">\(t(120) = 2.47, p = .040\)</span>, <span class="math inline">\(d_s\)</span> = 0.57, 95% CI [0.12, 1.01]. In summary, we found that overt retrieval resulted in better memory than restudying, but neither of these methods differed from delayed judgment.</p>
</section>
</section>
<section id="power" class="level1">
<h1>Power</h1>
<section id="calculate-power-with-webpower" class="level2">
<h2 class="anchored" data-anchor-id="calculate-power-with-webpower">Calculate Power with <code>WebPower</code></h2>
<p>Using the WebPower package, calculate the the number of participants per group we need to have 90% power in our model to detect a difference.</p>
<p>Note that most power calculators ask for Cohen’s <span class="math inline">\(f^2\)</span> instead of <span class="math inline">\(R^2\)</span>, so we’ll need to calculate that first.</p>
<p><span class="math inline">\(f^2 = R^2 / (1 - R^2)\)</span></p>
<p>How many participants do we need for our study?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>r.squared</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>f_squared <span class="ot">&lt;-</span> r_squared<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>r_squared)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># first, let's look at the help info for `wp.regression`</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>?wp.regression</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># students: fill in the arguments below</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># WebPower::wp.regression(n=XXX, p1=XXX, f2=XXX, alpha=XXX, power=XXX)</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>WebPower<span class="sc">::</span><span class="fu">wp.regression</span>(<span class="at">n=</span><span class="dv">200</span>, <span class="at">p1=</span><span class="dv">2</span>, <span class="at">f2=</span><span class="cn">NULL</span>, <span class="at">alpha=</span><span class="fl">0.05</span>, <span class="at">power=</span>.<span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Power for multiple regression

      n p1 p2         f2 alpha power
    200  2  0 0.06424069  0.05   0.9

URL: http://psychstat.org/regression</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># note: you can plug in `NULL` for different arguments if you have different questions</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulation-power-analysis-with-superpower" class="level2">
<h2 class="anchored" data-anchor-id="simulation-power-analysis-with-superpower">Simulation Power Analysis with <code>Superpower</code></h2>
<p>Book going over <a href="https://aaroncaldwell.us/SuperpowerBook/">Superpower</a></p>
<p>Reviewer 2 asked you to calculate the power of Tekin et al (2021) Experiment 1 after you ran it. Set up a study design using the <code>ANOVA_design</code> function from <code>Superpower</code>. Use the same means, SD, and n (use 40 per group as <code>SuperPower</code>cannot do unequal sample sizes for one-way designs) from their Experiment 1 study (excluding the one condition). Run a power analysis on this data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#first, let's look at what we need for this function</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>?ANOVA_design</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#create objects for each parameter</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>design <span class="ot">&lt;-</span> <span class="st">"3b"</span> <span class="co"># 3 levels of `condition` varying between subjects</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">40</span> <span class="co"># unequal ns dont work yet for this</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">50</span>,.<span class="dv">52</span>, .<span class="dv">43</span>)<span class="co"># each group mean</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>sd <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.17</span>, .<span class="dv">14</span>, <span class="fl">0.17</span>) <span class="co"># each group sd</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>label_list <span class="ot">=</span> <span class="fu">list</span>(<span class="st">"Condition"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Cue-JOL"</span>, <span class="st">"OR"</span>,<span class="st">"RS"</span>)) <span class="co"># labels for each group</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co">#now, use ANOVA_design to specify the parameters of the data</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>design_result <span class="ot">&lt;-</span> <span class="fu">ANOVA_design</span>(<span class="at">design =</span> design,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>                              <span class="at">n =</span> n,</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>                              <span class="at">mu =</span> mu, </span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sd =</span> sd, </span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>                              <span class="at">label_list =</span> label_list)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-lab-starter-key_files/figure-html/superpower-design-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#check out the simulated data!</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>design_result<span class="sc">$</span>dataframe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    subject              cond           y         Condition
1         1 Condition_Cue-JOL  0.69252099 Condition_Cue-JOL
2         2 Condition_Cue-JOL  0.49720399 Condition_Cue-JOL
3         3 Condition_Cue-JOL  0.55230923 Condition_Cue-JOL
4         4 Condition_Cue-JOL  0.66668120 Condition_Cue-JOL
5         5 Condition_Cue-JOL  0.33594245 Condition_Cue-JOL
6         6 Condition_Cue-JOL  0.73103689 Condition_Cue-JOL
7         7 Condition_Cue-JOL  0.33793054 Condition_Cue-JOL
8         8 Condition_Cue-JOL  0.54560764 Condition_Cue-JOL
9         9 Condition_Cue-JOL  0.57217923 Condition_Cue-JOL
10       10 Condition_Cue-JOL  0.31693457 Condition_Cue-JOL
11       11 Condition_Cue-JOL  0.57800839 Condition_Cue-JOL
12       12 Condition_Cue-JOL  0.63628858 Condition_Cue-JOL
13       13 Condition_Cue-JOL  0.28253712 Condition_Cue-JOL
14       14 Condition_Cue-JOL  0.55205711 Condition_Cue-JOL
15       15 Condition_Cue-JOL  0.24240975 Condition_Cue-JOL
16       16 Condition_Cue-JOL  0.70584713 Condition_Cue-JOL
17       17 Condition_Cue-JOL  0.28239038 Condition_Cue-JOL
18       18 Condition_Cue-JOL  0.37856297 Condition_Cue-JOL
19       19 Condition_Cue-JOL  0.54592166 Condition_Cue-JOL
20       20 Condition_Cue-JOL  0.48935782 Condition_Cue-JOL
21       21 Condition_Cue-JOL  0.44219857 Condition_Cue-JOL
22       22 Condition_Cue-JOL -0.05957806 Condition_Cue-JOL
23       23 Condition_Cue-JOL  0.65718998 Condition_Cue-JOL
24       24 Condition_Cue-JOL  0.31961976 Condition_Cue-JOL
25       25 Condition_Cue-JOL  0.34137581 Condition_Cue-JOL
26       26 Condition_Cue-JOL  0.57301414 Condition_Cue-JOL
27       27 Condition_Cue-JOL  0.32132320 Condition_Cue-JOL
28       28 Condition_Cue-JOL  0.72831508 Condition_Cue-JOL
29       29 Condition_Cue-JOL  0.45922955 Condition_Cue-JOL
30       30 Condition_Cue-JOL  0.42883182 Condition_Cue-JOL
31       31 Condition_Cue-JOL  0.28614533 Condition_Cue-JOL
32       32 Condition_Cue-JOL  0.82354635 Condition_Cue-JOL
33       33 Condition_Cue-JOL  0.46942865 Condition_Cue-JOL
34       34 Condition_Cue-JOL  0.45411970 Condition_Cue-JOL
35       35 Condition_Cue-JOL  0.46926928 Condition_Cue-JOL
36       36 Condition_Cue-JOL  0.57258634 Condition_Cue-JOL
37       37 Condition_Cue-JOL  0.40456265 Condition_Cue-JOL
38       38 Condition_Cue-JOL  0.15202280 Condition_Cue-JOL
39       39 Condition_Cue-JOL  0.47835097 Condition_Cue-JOL
40       40 Condition_Cue-JOL  0.80799486 Condition_Cue-JOL
41       41      Condition_OR  0.51260068      Condition_OR
42       42      Condition_OR  0.62506043      Condition_OR
43       43      Condition_OR  0.70329788      Condition_OR
44       44      Condition_OR  0.48131486      Condition_OR
45       45      Condition_OR  0.65674935      Condition_OR
46       46      Condition_OR  0.43000326      Condition_OR
47       47      Condition_OR  0.43342385      Condition_OR
48       48      Condition_OR  0.86329018      Condition_OR
49       49      Condition_OR  0.33248511      Condition_OR
50       50      Condition_OR  0.50472981      Condition_OR
51       51      Condition_OR  0.90580709      Condition_OR
52       52      Condition_OR  0.54519978      Condition_OR
53       53      Condition_OR  0.61757166      Condition_OR
54       54      Condition_OR  0.53154629      Condition_OR
55       55      Condition_OR  0.57279338      Condition_OR
56       56      Condition_OR  0.65752809      Condition_OR
57       57      Condition_OR  0.74055827      Condition_OR
58       58      Condition_OR  0.54872153      Condition_OR
59       59      Condition_OR  0.51608025      Condition_OR
60       60      Condition_OR  0.53749860      Condition_OR
61       61      Condition_OR  0.45493539      Condition_OR
62       62      Condition_OR  0.60497379      Condition_OR
63       63      Condition_OR  0.44011163      Condition_OR
64       64      Condition_OR  0.34184253      Condition_OR
65       65      Condition_OR  0.58914798      Condition_OR
66       66      Condition_OR  0.58198340      Condition_OR
67       67      Condition_OR  0.63053129      Condition_OR
68       68      Condition_OR  0.35509152      Condition_OR
69       69      Condition_OR  0.88505448      Condition_OR
70       70      Condition_OR  0.91111506      Condition_OR
71       71      Condition_OR  0.47975389      Condition_OR
72       72      Condition_OR  0.46004373      Condition_OR
73       73      Condition_OR  0.55737219      Condition_OR
74       74      Condition_OR  0.65073101      Condition_OR
75       75      Condition_OR  0.52024427      Condition_OR
76       76      Condition_OR  0.55400502      Condition_OR
77       77      Condition_OR  0.47238963      Condition_OR
78       78      Condition_OR  0.66626437      Condition_OR
79       79      Condition_OR  0.41674943      Condition_OR
80       80      Condition_OR  0.50958310      Condition_OR
81       81      Condition_RS  0.49104367      Condition_RS
82       82      Condition_RS  0.28949505      Condition_RS
83       83      Condition_RS  0.03938438      Condition_RS
84       84      Condition_RS  0.25871975      Condition_RS
85       85      Condition_RS  0.60047701      Condition_RS
86       86      Condition_RS  0.39704966      Condition_RS
87       87      Condition_RS  0.24516616      Condition_RS
88       88      Condition_RS  0.63087593      Condition_RS
89       89      Condition_RS  0.43796415      Condition_RS
90       90      Condition_RS  0.58632474      Condition_RS
91       91      Condition_RS  0.47785222      Condition_RS
92       92      Condition_RS  0.42468442      Condition_RS
93       93      Condition_RS  0.48842743      Condition_RS
94       94      Condition_RS  0.15460158      Condition_RS
95       95      Condition_RS  0.58916926      Condition_RS
96       96      Condition_RS  0.51249448      Condition_RS
97       97      Condition_RS  0.34025778      Condition_RS
98       98      Condition_RS  0.44921175      Condition_RS
99       99      Condition_RS  0.44319735      Condition_RS
100     100      Condition_RS  0.14150445      Condition_RS
101     101      Condition_RS  0.53432013      Condition_RS
102     102      Condition_RS  0.55545597      Condition_RS
103     103      Condition_RS  0.45354024      Condition_RS
104     104      Condition_RS  0.43027400      Condition_RS
105     105      Condition_RS  0.53089583      Condition_RS
106     106      Condition_RS  0.79403213      Condition_RS
107     107      Condition_RS  0.16935815      Condition_RS
108     108      Condition_RS  0.62673648      Condition_RS
109     109      Condition_RS  0.23692661      Condition_RS
110     110      Condition_RS  0.39853862      Condition_RS
111     111      Condition_RS  0.46095144      Condition_RS
112     112      Condition_RS  0.42774383      Condition_RS
113     113      Condition_RS  0.45488629      Condition_RS
114     114      Condition_RS  0.41583288      Condition_RS
115     115      Condition_RS  0.20662822      Condition_RS
116     116      Condition_RS  0.46054074      Condition_RS
117     117      Condition_RS  0.84325284      Condition_RS
118     118      Condition_RS  0.31403952      Condition_RS
119     119      Condition_RS  0.42098287      Condition_RS
120     120      Condition_RS  0.41088342      Condition_RS</code></pre>
</div>
</div>
<p>Now, let’s check out how much power we have. Here, we will run our analysis many times (nsims below) and seeing how many of those times we get a significant result.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>nsims<span class="ot">=</span><span class="dv">500</span> <span class="co">#number of times we do this should be larger than this, but it takes a while to run so we'll stick with 500 for this example!</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>power_result <span class="ot">&lt;-</span> <span class="fu">ANOVA_power</span>(design_result, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">nsims =</span> nsims, </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">seed =</span> <span class="dv">1234</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Power and Effect sizes for ANOVA tests
                power effect_size
anova_Condition  66.8     0.06962

Power and Effect sizes for pairwise comparisons (t-tests)
                                 power effect_size
p_Condition_Cue-JOL_Condition_OR  10.0      0.1379
p_Condition_Cue-JOL_Condition_RS  43.2     -0.4102
p_Condition_OR_Condition_RS       72.2     -0.5867</code></pre>
</div>
</div>
<p>What is our power to detect the overall effect of <code>Condition</code>? What about the pairwise comparisons between the groups?</p>
<p>ANSWER: To detect the effect of Condition we have only 66.8% power (Yikes). To detect the cue-JOL vs.&nbsp;overt difference we have 10.0% power. To detect the Cue-JOL vs.&nbsp;Restudy difference we have 43.2% power. Finally, to detect the overt and restudy difference we have power of 72.2%.</p>
<p>What kind of power analysis would this be?</p>
<p>ANSWER: We’re doing it after we ran the study – Post-hoc</p>
<p>What do you think of the power for this study design?</p>
<p>ANSWER: Not very well powered study.</p>
</section>
</section>
<section id="now-we-want-to-run-a-replication-study.-lets-plan-a-study-where-we-want-to-collect-100-ps-per-group." class="level1">
<h1>Now, we want to run a replication study. Let’s plan a study where we want to collect 100 Ps per group.</h1>
<p>Change <code>ANOVA_design</code> to reflect <em>just this difference</em>. Set N = 100.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create objects for each parameter</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>design <span class="ot">&lt;-</span> <span class="st">"3b"</span> <span class="co"># 3 levels of `condition` varying between subjects</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="co"># unequal ns dont work yet for this</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">50</span>,.<span class="dv">52</span>, .<span class="dv">43</span>)<span class="co"># each group mean</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>sd <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.17</span>, .<span class="dv">14</span>, <span class="fl">0.17</span>) <span class="co"># each group sd</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>label_list <span class="ot">=</span> <span class="fu">list</span>(<span class="st">"condition"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Cue-JOL"</span>, <span class="st">"OR"</span>,<span class="st">"RS"</span>)) <span class="co"># labels for each group</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co">#now, use ANOVA_design to specify the parameters of the data</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>design_result <span class="ot">&lt;-</span> <span class="fu">ANOVA_design</span>(<span class="at">design =</span> design,</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>                              <span class="at">n =</span> n,</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>                              <span class="at">mu =</span> mu, </span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sd =</span> sd, </span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>                              <span class="at">label_list =</span> label_list)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-lab-starter-key_files/figure-html/new-design-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>nsims<span class="ot">=</span><span class="dv">500</span><span class="co"># number of times we do this should be larger than this!</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>power_result_vig_2 <span class="ot">&lt;-</span> <span class="fu">ANOVA_power</span>(design_result, </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">nsims =</span> nsims, </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">seed =</span> <span class="dv">1234</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Power and Effect sizes for ANOVA tests
                power effect_size
anova_condition    97     0.06225

Power and Effect sizes for pairwise comparisons (t-tests)
                                 power effect_size
p_condition_Cue-JOL_condition_OR  14.8      0.1320
p_condition_Cue-JOL_condition_RS  83.6     -0.4179
p_condition_OR_condition_RS       97.8     -0.5890</code></pre>
</div>
</div>
<p>What would our power be using the current study parameters to detect overall effect? How about each pairwise comparison?</p>
<p>ANSWER: To detect the effect of Condition we have 97% power – much better! To detect the cue-JOL vs.&nbsp;overt difference we have 14.8% power. To detect the Cue-JOL vs.&nbsp;Restudy difference we have 83.6% power. Finally, to detect the overt and restudy difference we have power of 97.8%.</p>
<p>What kind of power analysis would this be?</p>
<p>ANSWER: We’re doing it before we run the replication, so its a priori – good!</p>
<p>What do you think of the power for this study design?</p>
<p>ANSWER: Much better, except for the effect of JOL vs OR is still very low. Why? Look back at Cohen’s d values - effect for JOL vs OR is only -0.16 while others are .41 and .58 (much larger)</p>
</section>
<section id="lets-say-i-want-to-power-the-study-to-be-able-to-detect-a-.05-point-difference-on-the-final-test-between-the-cue-only-jols-and-overt-retrieval-groups-e.g.-the-difference-between-their-means." class="level1">
<h1>Let’s say I want to power the study to be able to detect a .05 point difference on the final test between the Cue-Only JOLs and Overt Retrieval groups (e.g., the difference between their means).</h1>
<p>Change <code>ANOVA_design</code> to reflect <em>just this difference</em>. Set N = 40.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>design <span class="ot">&lt;-</span> <span class="st">"2b"</span> <span class="co">#now there are only 2 levels of the variable!</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">40</span> <span class="co">#unequal ns dont work yet for this</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">50</span>,.<span class="dv">55</span>) <span class="co">#each group mean</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>sd <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.17</span>, .<span class="dv">14</span>) <span class="co">#each group sd</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>label_list <span class="ot">=</span> <span class="fu">list</span>(<span class="st">"condition"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Cue-JOL"</span>, <span class="st">"OR"</span>)) <span class="co"># labels for each group</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>design_result <span class="ot">&lt;-</span> <span class="fu">ANOVA_design</span>(<span class="at">design =</span> design,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>                              <span class="at">n =</span> n,</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>                              <span class="at">mu =</span> mu, </span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sd =</span> sd, </span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>                              <span class="at">label_list =</span> label_list)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-lab-starter-key_files/figure-html/new-design-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>nsims<span class="ot">=</span><span class="dv">500</span> <span class="co">#number of times we do this should be larger than this!</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>power_result <span class="ot">&lt;-</span> <span class="fu">ANOVA_power</span>(design_result, </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">nsims =</span> nsims, </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">seed =</span> <span class="dv">1234</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Power and Effect sizes for ANOVA tests
                power effect_size
anova_condition  30.2     0.03817

Power and Effect sizes for pairwise comparisons (t-tests)
                                 power effect_size
p_condition_Cue-JOL_condition_OR  30.2      0.3305</code></pre>
</div>
</div>
<p>What is our power to detect a .05 point difference with 40 per group?</p>
<p>ANSWER: We have 30% power (not great!)</p>
</section>
<section id="plot-a-power-curve-just-for-this-difference.-what-sample-size-is-needed-to-achieve-90-power" class="level1">
<h1>Plot a power curve just for this difference. What sample size is needed to achieve 90% power?</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_power</span>(design_result, <span class="at">min_n =</span> <span class="dv">10</span>, <span class="at">max_n =</span> <span class="dv">400</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-lab-starter-key_files/figure-html/plot-power-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Achieved Power and Sample Size for ANOVA-level effects
   variable                  label   n achieved_power desired_power
1 condition Desired Power Achieved 205          90.03            90</code></pre>
</div>
</div>
<p>How many participants would you need to achieve 90% power?</p>
<p>ANSWER: You need 205 participants to have 90% power to detect a .05 difference between the two conditions.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>