<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 12: Lab Starter (KEY)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="12-lab-starter-key-shared_files/libs/clipboard/clipboard.min.js"></script>
<script src="12-lab-starter-key-shared_files/libs/quarto-html/quarto.js"></script>
<script src="12-lab-starter-key-shared_files/libs/quarto-html/popper.min.js"></script>
<script src="12-lab-starter-key-shared_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="12-lab-starter-key-shared_files/libs/quarto-html/anchor.min.js"></script>
<link href="12-lab-starter-key-shared_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="12-lab-starter-key-shared_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="12-lab-starter-key-shared_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="12-lab-starter-key-shared_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="12-lab-starter-key-shared_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 12: Lab Starter (KEY)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="purpose" class="level1">
<h1>Purpose</h1>
<p>In today’s lab, we will work through a set of analyses that will:</p>
<ol type="1">
<li>Highlight core concepts of multilevel variation.</li>
<li>Illustrate how group-level predictors function.</li>
<li>Contrast multilevel and single-level models.</li>
<li>Facilitate interpretation of the parameters of multilevel models.</li>
</ol>
<p>For today’s lab, you will only need tidyverse!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.5.2</code></pre>
</div>
</div>
</section>
<section id="research-scenario" class="level1">
<h1>Research scenario</h1>
<p>Today’s dataset examines the effect of time spent on math homework on math achievement scores.</p>
<section id="read-in-the-data" class="level2">
<h2 class="anchored" data-anchor-id="read-in-the-data">Read in the data</h2>
<p>Today’s dataset is called <code>NELS88.csv</code>. Let’s read it in and name it <code>nels</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>nels <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/NELS88.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="examine-the-data" class="level2">
<h2 class="anchored" data-anchor-id="examine-the-data">Examine the Data</h2>
<ul>
<li>Use <code>View()</code> to examine the full dataset</li>
<li>Use <code>str()</code> to look at the structure of the data</li>
<li>Use <code>head()</code> to look at the first few rows of the data</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(nels)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(nels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [260 × 15] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Schoolid       : num [1:260] 7472 7472 7472 7472 7472 ...
 $ studentid      : num [1:260] 3 8 13 17 27 28 30 36 37 42 ...
 $ sex            : num [1:260] 2 1 1 1 2 2 2 1 2 2 ...
 $ race           : num [1:260] 4 4 4 4 4 4 4 4 4 4 ...
 $ timeonmath     : num [1:260] 1 0 0 1 2 1 5 1 1 2 ...
 $ schooltype     : chr [1:260] "public" "public" "public" "public" ...
 $ ses            : num [1:260] -0.13 -0.39 -0.8 -0.72 -0.74 -0.58 -0.83 -0.51 -0.56 0.21 ...
 $ parented       : num [1:260] 2 2 2 2 2 2 2 3 2 3 ...
 $ mathscore      : num [1:260] 48 48 53 42 43 57 33 64 36 56 ...
 $ classstruct    : num [1:260] 2 2 2 2 2 2 2 2 2 2 ...
 $ schoolsize     : num [1:260] 3 3 3 3 3 3 3 3 3 3 ...
 $ urbanicity     : num [1:260] 2 2 2 2 2 2 2 2 2 2 ...
 $ geography      : num [1:260] 2 2 2 2 2 2 2 2 2 2 ...
 $ percentminority: num [1:260] 0 0 0 0 0 0 0 0 0 0 ...
 $ stuteachratio  : num [1:260] 19 19 19 19 19 19 19 19 19 19 ...
 - attr(*, "spec")=
  .. cols(
  ..   Schoolid = col_double(),
  ..   studentid = col_double(),
  ..   sex = col_double(),
  ..   race = col_double(),
  ..   timeonmath = col_double(),
  ..   schooltype = col_character(),
  ..   ses = col_double(),
  ..   parented = col_double(),
  ..   mathscore = col_double(),
  ..   classstruct = col_double(),
  ..   schoolsize = col_double(),
  ..   urbanicity = col_double(),
  ..   geography = col_double(),
  ..   percentminority = col_double(),
  ..   stuteachratio = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 15
  Schoolid studentid   sex  race timeonmath schooltype   ses parented mathscore
     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1     7472         3     2     4          1 public     -0.13        2        48
2     7472         8     1     4          0 public     -0.39        2        48
3     7472        13     1     4          0 public     -0.8         2        53
4     7472        17     1     4          1 public     -0.72        2        42
5     7472        27     2     4          2 public     -0.74        2        43
6     7472        28     2     4          1 public     -0.58        2        57
# ℹ 6 more variables: classstruct &lt;dbl&gt;, schoolsize &lt;dbl&gt;, urbanicity &lt;dbl&gt;,
#   geography &lt;dbl&gt;, percentminority &lt;dbl&gt;, stuteachratio &lt;dbl&gt;</code></pre>
</div>
</div>
<p>As we discussed in lecture on Tuesday, the world we live in is highly interdependent.</p>
<blockquote class="blockquote">
<p>Question: What kind of clustering might we have in these data?</p>
</blockquote>
</section>
<section id="for-our-analyses-we-want-schoolid-to-be-a-factor.-lets-make-that-change-to-the-data." class="level2">
<h2 class="anchored" data-anchor-id="for-our-analyses-we-want-schoolid-to-be-a-factor.-lets-make-that-change-to-the-data.">For our analyses, we want Schoolid to be a factor. Let’s make that change to the data.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>nels <span class="ot">&lt;-</span> nels <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Schoolid =</span> <span class="fu">as.factor</span>(Schoolid))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="we-will-start-by-discussing-some-key-concepts-related-to-multilevel-models." class="level2">
<h2 class="anchored" data-anchor-id="we-will-start-by-discussing-some-key-concepts-related-to-multilevel-models.">We will start by discussing some key concepts related to multilevel models.</h2>
</section>
<section id="disaggregation-versus-aggregation" class="level2">
<h2 class="anchored" data-anchor-id="disaggregation-versus-aggregation">Disaggregation versus Aggregation</h2>
<p>In classical analyses (e.g., ANOVA), we often aggregate to the group level (e.g., calculate a mean that averages across all trials for a participant). While disaggregated analyses allow us to keep all of the data that we collect, they may also ignore potential clustering in the data.</p>
<p>Aggregation: Ignores within-level data (discards within-group variability)</p>
<p>Disaggregation: Ignores group-level data (discards between-group variability)</p>
<p><em>Disaggregation:</em> Estimate a disaggregated model predicting math achievement from time spent on math homework each week. Since disaggregation ignores group-level data, we will not use the <code>schoolid</code> variable in our regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># students: run the disaggregated model</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># disag &lt;- lm(XXX ~ XXX, data=nels)</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>disag <span class="ot">&lt;-</span> <span class="fu">lm</span>(mathscore <span class="sc">~</span> timeonmath, <span class="at">data=</span>nels)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(disag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mathscore ~ timeonmath, data = nels)

Residuals:
     Min       1Q   Median       3Q      Max 
-28.9331  -6.6457   0.3543   7.0669  20.9261 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  44.0739     0.9886   44.58   &lt;2e-16 ***
timeonmath    3.5719     0.3882    9.20   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.682 on 258 degrees of freedom
Multiple R-squared:  0.247, Adjusted R-squared:  0.2441 
F-statistic: 84.64 on 1 and 258 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(disag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: mathscore
            Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
timeonmath   1  7933.8  7933.8  84.644 &lt; 2.2e-16 ***
Residuals  258 24182.8    93.7                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Question: What do the results suggest?</p>
</blockquote>
<blockquote class="blockquote">
<p>Question: What is the problem with conducting the analysis in this manner?</p>
</blockquote>
<p><em>Aggregation:</em> Estimate an aggregated model predicting mean math achievement from mean hours spent on homework each week. Since aggregation ignores individual-level data, we need to compute the mean math score and the mean time spent on math homework for each of the 10 schools.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#First, get the average math score and time on math for each school</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># students: use `group_by` and `summarise()` to generate a new dataset with these values</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># nelsagg &lt;- nels %&gt;% </span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   group_by(XXX) %&gt;% </span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   summarise(mathagg = mean(XXX, na.rm = TRUE),</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co">#             timeagg = mean(XXX, na.rm = TRUE))</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>nelsagg <span class="ot">&lt;-</span> nels <span class="sc">%&gt;%</span> </span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Schoolid) <span class="sc">%&gt;%</span> </span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mathagg =</span> <span class="fu">mean</span>(mathscore, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">timeagg =</span> <span class="fu">mean</span>(timeonmath, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Now, using the aggregated data, run the model</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>agg <span class="ot">&lt;-</span> <span class="fu">lm</span>(mathagg <span class="sc">~</span> timeagg, <span class="at">data=</span>nelsagg)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(agg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mathagg ~ timeagg, data = nelsagg)

Residuals:
   Min     1Q Median     3Q    Max 
-9.575 -1.105 -0.233  3.237  6.370 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   40.018      4.530   8.834 2.12e-05 ***
timeagg        4.982      2.415   2.063   0.0731 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.048 on 8 degrees of freedom
Multiple R-squared:  0.3472,    Adjusted R-squared:  0.2656 
F-statistic: 4.254 on 1 and 8 DF,  p-value: 0.07307</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(agg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: mathagg
          Df Sum Sq Mean Sq F value  Pr(&gt;F)  
timeagg    1 108.39 108.385  4.2541 0.07307 .
Residuals  8 203.82  25.477                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Question: What do the results suggest?</p>
</blockquote>
<blockquote class="blockquote">
<p>Question: What is the problem with conducting the analysis in this manner?</p>
</blockquote>
</section>
<section id="assessing-the-effect-of-the-grouping-variable." class="level2">
<h2 class="anchored" data-anchor-id="assessing-the-effect-of-the-grouping-variable.">Assessing the effect of the grouping variable.</h2>
<p>We might want to know how much of an effect our grouping variable (<code>Schoolid</code>) has on our outcome (<code>mathscore</code>). To assess this, we can use the ICC or intraclass correlation coefficient. The ICC is an index of within-group similarity.</p>
<p>Recall that:</p>
<p>Total Variance = Between Group Variance + Within Group Variance</p>
<p>The ICC is calculated as:</p>
<p>ICC = Between Group Variance / Total Variance</p>
<p>or</p>
<p>ICC = Between Group Variance / (Between Group Variance + Within Group Variance)</p>
<p>In summary, we can use the ICC to answer the question: How much of the total variance in our dependent variable can be accounted for by the grouping effect?</p>
<blockquote class="blockquote">
<p>Question: How can we get the between-schools variability, within-schools variability, and the total variability in math achievement?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run a one-way ANOVA predicting mathscore from Schoolid</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>icc_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mathscore <span class="sc">~</span> Schoolid, <span class="at">data=</span>nels)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(icc_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mathscore ~ Schoolid, data = nels)

Residuals:
     Min       1Q   Median       3Q      Max 
-20.2500  -5.7052  -0.6423   4.4909  24.6667 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    45.7391     1.7735  25.790  &lt; 2e-16 ***
Schoolid7829   -3.5891     2.6005  -1.380  0.16877    
Schoolid7930    7.5109     2.4819   3.026  0.00273 ** 
Schoolid24725  -2.1937     2.5365  -0.865  0.38795    
Schoolid25456   4.1245     2.5365   1.626  0.10519    
Schoolid25642   0.6609     2.6005   0.254  0.79960    
Schoolid62821  17.0818     2.0555   8.310 6.13e-15 ***
Schoolid68448   3.9275     2.5672   1.530  0.12730    
Schoolid68493   0.5942     2.5672   0.231  0.81715    
Schoolid72292   2.1109     2.6005   0.812  0.41773    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.506 on 250 degrees of freedom
Multiple R-squared:  0.4369,    Adjusted R-squared:  0.4166 
F-statistic: 21.55 on 9 and 250 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>icc_aov <span class="ot">&lt;-</span> <span class="fu">anova</span>(icc_mod)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>icc_aov</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: mathscore
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Schoolid    9  14030 1558.95  21.549 &lt; 2.2e-16 ***
Residuals 250  18086   72.34                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Question: What is the sums of squares for the effect of school? How can we calculate the total sums of squares?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract the ss_between and ss_total</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>ss_b <span class="ot">&lt;-</span> icc_aov[<span class="dv">1</span>,<span class="dv">2</span>]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>ss_t <span class="ot">&lt;-</span>(icc_aov[<span class="dv">1</span>,<span class="dv">2</span>] <span class="sc">+</span> icc_aov[<span class="dv">2</span>,<span class="dv">2</span>])</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the ICC</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># students: calculate the ICC</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># ICC &lt;- XXX/XXX</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>ICC <span class="ot">&lt;-</span> ss_b<span class="sc">/</span>ss_t</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>ICC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4368624</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># turn the ICC into a percentage</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"The grouping factor accounts for"</span>, <span class="fu">round</span>(ICC<span class="sc">*</span><span class="dv">100</span>, <span class="at">digits=</span><span class="dv">2</span>),<span class="st">"% of the variance in math scores."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The grouping factor accounts for 43.69 % of the variance in math scores."</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Question: What does this mean?</p>
</blockquote>
<p>In the <em>disaggregated model</em> we ran above (predicting <code>mathscore</code> from <code>timeonmath</code>), we are assuming that school (the grouping variable) explains 0% of the variance in math scores. This assumes that we have 260 unique values (the number of entries in our data).</p>
<p>In the <em>aggregated model</em>, we ran above (using <code>mathscore</code> from <code>timeonmath</code> averaged for each school), we are assuming that school (the grouping variable) explains 100% of the variance in math scores (i.e., that everyone in the school has the same math score). This assumes that we have 10 unique values (the number of schools in our data).</p>
<p>However, the amount of unique data we have falls actually somewhere in the middle.</p>
</section>
<section id="examining-variability-in-intercepts-and-slopes" class="level2">
<h2 class="anchored" data-anchor-id="examining-variability-in-intercepts-and-slopes">Examining Variability in Intercepts and Slopes</h2>
<p>Because we have a high ICC for the group effect, it’s useful to visualize our data to see if they vary in slopes, intercepts, or both. This will help us understand the source of the group effect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>nels <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> timeonmath, <span class="at">y =</span> mathscore)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Schoolid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="12-lab-starter-key-shared_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>nels <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> timeonmath, <span class="at">y =</span> mathscore, <span class="at">color =</span> Schoolid)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="12-lab-starter-key-shared_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Question: From these plots, what can you say about the slopes and intercepts?</p>
</blockquote>
<p>If there is real variability due to the grouping effect, we usually want to try to figure out what characteristics of the group (i.e., a school) predict its regression line (i.e., its slope and intercept) so we can say something more substantial than just “the way time spent on homework predicts math scores is different school to school”.</p>
</section>
<section id="slopes-and-intercepts-as-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="slopes-and-intercepts-as-outcomes">Slopes and Intercepts as Outcomes</h2>
<p>First, let’s run an ANOVA-style regression to see whether <code>Schoolid</code> improves our model fit over a model with just <code>timeonmath</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># students: run this model (hint: we're just adding ONE additional predictor!)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model1 &lt;- lm(XXX, data = nels)</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mathscore <span class="sc">~</span> timeonmath <span class="sc">+</span> Schoolid, <span class="at">data =</span> nels)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mathscore ~ timeonmath + Schoolid, data = nels)

Residuals:
     Min       1Q   Median       3Q      Max 
-20.4496  -5.0547  -0.1313   4.7138  27.8711 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    42.7664     1.7587  24.317  &lt; 2e-16 ***
timeonmath      2.1366     0.3836   5.570 6.60e-08 ***
Schoolid7829   -5.6375     2.4845  -2.269  0.02412 *  
Schoolid7930    6.5664     2.3512   2.793  0.00563 ** 
Schoolid24725  -2.7173     2.3985  -1.133  0.25834    
Schoolid25456   5.2519     2.4052   2.184  0.02993 *  
Schoolid25642   1.1764     2.4589   0.478  0.63275    
Schoolid62821  13.0068     2.0754   6.267 1.61e-09 ***
Schoolid68448   2.4235     2.4406   0.993  0.32169    
Schoolid68493   0.7181     2.4258   0.296  0.76746    
Schoolid72292   1.6650     2.4585   0.677  0.49888    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.037 on 249 degrees of freedom
Multiple R-squared:  0.4992,    Adjusted R-squared:  0.4791 
F-statistic: 24.83 on 10 and 249 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: mathscore
            Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
timeonmath   1  7933.8  7933.8 122.837 &lt; 2.2e-16 ***
Schoolid     9  8100.4   900.0  13.935 &lt; 2.2e-16 ***
Residuals  249 16082.4    64.6                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Question: What does this model tell us about the impact of <code>Schoolid</code> on <code>mathscore</code>? What does it suggest about the intercepts? …the slopes?</p>
</blockquote>
<blockquote class="blockquote">
<p>Question: What do I need to do to get information about the effect of <code>Schoolid</code> on the slopes (i.e., the relation between <code>timeonmath</code> and <code>mathscore</code>)?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mathscore <span class="sc">~</span> timeonmath <span class="sc">*</span> Schoolid, <span class="at">data =</span> nels)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mathscore ~ timeonmath * Schoolid, data = nels)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.3049  -3.4192  -0.2385   4.2495  16.8703 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               50.6835     2.2157  22.875  &lt; 2e-16 ***
timeonmath                -3.5538     1.2523  -2.838 0.004931 ** 
Schoolid7829              -1.6713     3.7914  -0.441 0.659757    
Schoolid7930             -11.9335     3.4121  -3.497 0.000560 ***
Schoolid24725            -16.2897     3.0526  -5.336 2.19e-07 ***
Schoolid25456              3.2551     3.0693   1.061 0.289974    
Schoolid25642             -1.4246     3.4066  -0.418 0.676187    
Schoolid62821              8.5267     2.8185   3.025 0.002755 ** 
Schoolid68448            -14.6282     3.7803  -3.870 0.000141 ***
Schoolid68493            -12.1635     3.3997  -3.578 0.000419 ***
Schoolid72292            -12.9696     3.1476  -4.121 5.21e-05 ***
timeonmath:Schoolid7829    0.6337     1.7006   0.373 0.709765    
timeonmath:Schoolid7930   11.4629     1.7428   6.577 2.97e-10 ***
timeonmath:Schoolid24725   9.1465     1.5759   5.804 2.04e-08 ***
timeonmath:Schoolid25456  -1.1646     2.2340  -0.521 0.602629    
timeonmath:Schoolid25642   1.0677     2.2365   0.477 0.633499    
timeonmath:Schoolid62821   4.6484     1.3372   3.476 0.000603 ***
timeonmath:Schoolid68448  10.0501     1.7994   5.585 6.31e-08 ***
timeonmath:Schoolid68493   9.4138     2.0381   4.619 6.29e-06 ***
timeonmath:Schoolid72292   9.8888     1.6367   6.042 5.77e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.564 on 240 degrees of freedom
Multiple R-squared:  0.678, Adjusted R-squared:  0.6525 
F-statistic: 26.59 on 19 and 240 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: mathscore
                     Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
timeonmath            1  7933.8  7933.8 184.111 &lt; 2.2e-16 ***
Schoolid              9  8100.4   900.0  20.886 &lt; 2.2e-16 ***
timeonmath:Schoolid   9  5740.2   637.8  14.801 &lt; 2.2e-16 ***
Residuals           240 10342.2    43.1                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Question: Does <code>Schoolid</code> impact the intercepts, the slope, or both?</p>
</blockquote>
<p>Now we know that there is significant between-school variance in both the intercepts and the slopes and can try to predict this variance using school-level predictors. In this dataset, we have a variable that indicates whether the school is public or private (<code>schooltype</code>).</p>
<p>First, we need to find the unique intercept and slope for each of the 10 schools.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This script tells R to run our regression (model) for each school. It will then save the coefficents (i.e., the slopes and the intercepts) from each regression. The saved intercepts and slopes will be in the object "slopesints".</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>slopesints <span class="ot">&lt;-</span> nels <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Schoolid, schooltype) <span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">intercept =</span> <span class="fu">coef</span>(<span class="fu">lm</span>(mathscore <span class="sc">~</span> timeonmath))[<span class="dv">1</span>],</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">slope =</span> <span class="fu">coef</span>(<span class="fu">lm</span>(mathscore <span class="sc">~</span> timeonmath))[<span class="dv">2</span>]</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="co"># make `schooltype` a factor</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>slopesints <span class="ot">&lt;-</span> slopesints <span class="sc">%&gt;%</span> </span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">schooltype =</span> <span class="fu">as.factor</span>(schooltype))</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a><span class="co"># check out the contrasts</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(slopesints<span class="sc">$</span>schooltype) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        private
public        0
private       1</code></pre>
</div>
</div>
<p>Now, let’s try to predict the <em>intercepts</em> from whether a school is public or private.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># students: run a model predicting the `intercept` from `schooltype`</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># int &lt;- lm(XXX, data=slopesints)</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>int <span class="ot">&lt;-</span> <span class="fu">lm</span>(intercept <span class="sc">~</span> schooltype, <span class="at">data=</span>slopesints)</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = intercept ~ schooltype, data = slopesints)

Residuals:
   Min     1Q Median     3Q    Max 
-8.754 -5.232 -2.199  6.050 10.791 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         43.147      2.478   17.41 1.21e-07 ***
schooltypeprivate   16.063      7.837    2.05   0.0745 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.435 on 8 degrees of freedom
Multiple R-squared:  0.3443,    Adjusted R-squared:  0.2624 
F-statistic: 4.201 on 1 and 8 DF,  p-value: 0.07455</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Question: What is the regression equation predicting intercept from school type?</p>
</blockquote>
<blockquote class="blockquote">
<p>Question: What is the expected math achievement for a private school? How about for a public school?</p>
</blockquote>
<blockquote class="blockquote">
<p>Question: What is the implied “time spent on homework” in this model?</p>
</blockquote>
<blockquote class="blockquote">
<p>Question: The effect of school type (the slope in this model) has a p value of .07. What does this mean?</p>
</blockquote>
<p>Now, let’s try to predict the <em>slopes</em> from whether a school is public or private.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>slope <span class="ot">&lt;-</span> <span class="fu">lm</span>(slope<span class="sc">~</span>schooltype,<span class="at">data=</span>slopesints)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slope)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = slope ~ schooltype, data = slopesints)

Residuals:
   Min     1Q Median     3Q    Max 
-6.776 -4.869  1.768  4.159  5.852 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)         2.0572     1.7560   1.172    0.275
schooltypeprivate  -0.9626     5.5530  -0.173    0.867

Residual standard error: 5.268 on 8 degrees of freedom
Multiple R-squared:  0.003742,  Adjusted R-squared:  -0.1208 
F-statistic: 0.03005 on 1 and 8 DF,  p-value: 0.8667</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Question: What is the regression equation predicting slope from school type?</p>
</blockquote>
<blockquote class="blockquote">
<p>Question: What is the relationship (slope) between time spent on homework and math achievement for a private school? How about for a public school?</p>
</blockquote>
<p>For public schools, each 1 unit increase in time spent on homework corresponds to a 2.06 - 0.96 = 1.10 increase in math achievement.</p>
<blockquote class="blockquote">
<p>Question: Is the relationship (slope) significantly different for the two types of schools?</p>
</blockquote>
<blockquote class="blockquote">
<p>Question: Look back at the plot. Why do you think the effect school type on the slope wasn’t significant? The lines look like there are different slopes.</p>
</blockquote>
<blockquote class="blockquote">
<p>Also, look what happens if I fill the lines by school type. What do you notice?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>nels <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> timeonmath, <span class="at">y =</span> mathscore, <span class="at">color =</span> schooltype, <span class="at">group =</span> Schoolid)) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="12-lab-starter-key-shared_files/figure-html/plot-by-schooltype-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<p>You might be asking: Why do we need multilevel models? Can we just do this slopes and intercepts as outcomes analysis?</p>
<blockquote class="blockquote">
<p>TL;DR: Multilevel models are needed because treating slopes and intercepts as outcomes in a single-level regression ignores the hierarchical structure of the data, leading to biased estimates and incorrect standard errors; MLM addresses this by modeling nested data with random effects that capture within- and between-group variability and account for non-independence.</p>
</blockquote>
<p>While the idea of intercepts and slopes being outcomes is central to understanding what MLM does, simply treating them as outcomes in a standard single-level regression wouldn’t capture the crucial aspects and benefits of running a full multilevel model. Here’s why:</p>
<ol type="1">
<li>Ignoring the Hierarchical Structure and Dependencies:</li>
</ol>
<ul>
<li><p>Non-Independence of Errors: In hierarchical data, observations within the same group are likely to be more similar to each other than observations from different groups. This violates the assumption of independence of errors in standard regression. Treating intercepts and slopes as outcomes in a single-level model wouldn’t account for this non-independence, leading to:</p></li>
<li><p>Underestimated Standard Errors: This can result in inflated Type I error rates (incorrectly rejecting the null hypothesis).</p></li>
<li><p>Inaccurate Statistical Significance: Conclusions about the effects of predictors might be unreliable.</p></li>
</ul>
<p>Ignoring Group-Level Variance: A single-level model wouldn’t explicitly model the variance between groups in their intercepts and slopes. MLM quantifies this variance, providing valuable information about the extent to which groups differ.</p>
<ol start="2" type="1">
<li>Inefficient and Biased Estimates:</li>
</ol>
<ul>
<li><p>Pooling Data Inappropriately: Treating intercepts and slopes as outcomes in a single-level model would essentially involve estimating separate intercepts and slopes for each group without the benefits of partial pooling (also known as shrinkage) that MLM offers.</p></li>
<li><p>Lack of Shrinkage: MLM uses information from all groups to inform the estimates for each individual group. Groups with less data are “shrunk” towards the overall average, leading to more stable and reliable estimates, especially for groups with small sample sizes. A single-level approach wouldn’t have this borrowing of strength across groups.</p></li>
<li><p>Increased Number of Parameters: Estimating separate intercepts and slopes for each group in a single-level model significantly increases the number of parameters to be estimated, potentially leading to overfitting, especially with a large number of groups and small group sizes. MLM estimates variance components instead of individual group parameters, leading to a more parsimonious model.</p></li>
</ul>
<ol start="3" type="1">
<li>Inability to Model Group-Level Predictors of Intercepts and Slopes:</li>
</ol>
<ul>
<li><p>The “Why” Behind the Variation: The core strength of MLM is its ability to explain why intercepts and slopes vary across groups by including group-level predictors. A single-level model treating intercepts and slopes as outcomes wouldn’t allow you to directly model how group characteristics (e.g., school resources, hospital size) influence these group-specific parameters.</p></li>
<li><p>Cross-Level Interactions: MLM allows for the examination of how group-level variables moderate the relationships between individual-level predictors and the outcome (cross-level interactions). This is impossible to model directly in a single-level framework treating intercepts and slopes as simple outcomes.</p></li>
</ul>
<ol start="4" type="1">
<li>Conceptual Misunderstanding of Random Effects:</li>
</ol>
<ul>
<li>Fixed vs.&nbsp;Random: Treating each group’s intercept and slope as a fixed parameter in a single-level model implies that these are the only groups of interest and that their specific values are the primary focus. MLM, with its random effects, assumes that the observed groups are a sample from a larger population of groups, and we are interested in the distribution of intercepts and slopes in that population.</li>
</ul>
<p>In essence, while the idea of intercepts and slopes varying across groups is the foundation of MLM, simply trying to estimate separate intercepts and slopes for each group in a standard regression ignores the fundamental principles of hierarchical data analysis, leading to statistical problems and a loss of valuable insights into the group-level influences.</p>
<p>MLM provides a statistically rigorous and conceptually sound framework for simultaneously modeling individual-level relationships and the variation and predictors of group-level intercepts and slopes, while accounting for the non-independence of data within groups. It’s not just about seeing intercepts and slopes as outcomes; it’s about modeling the structure of that variation.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>