---
title: "PSY515: Module 1 Quiz"
format: 
  revealjs:
    multiplex: true
    slide-number: true
    incremental: true
    theme: simple
    touch: true
    code-overflow: wrap
execute:
  echo: true
editor: visual
---

## Module 1 Quiz!

Q1: What is **one** reason that we describe our data?

::: notes
find errors in data entry or collection understand the data explore descriptive research questions
:::

------------------------------------------------------------------------

## Module 1 Quiz!

Q2: Distributions are most often described by their...

::: nonincremental
-   A. mean and median
-   B. variance and standard deviation
-   C. center and spread
-   D. color and shape
:::

::: notes
we want to describe the center and spread most often the mean and variance or the mean and standard deviation, these are used in most statistical tests
:::

------------------------------------------------------------------------

## Module 1 Quiz!

Q3: I want to calculate a measure of spread in my distribution, so I calculate each score's deviation from the mean (i.e., x - mean) and then I add those scores together. What do I get?

::: nonincremental
-   A. The variance
-   B. The standard deviation
-   C. The range
-   D. Zero
:::

::: notes
deviations from the mean sum to zero, this is why we use the sum of squared deviations
:::

------------------------------------------------------------------------

## Module 1 Quiz!

Q4: What happens to the mean in a skewed distribution?

::: notes
gets pulled toward the tail so, what might we prefer to use? A: median becuase it represents the bulk of the data
:::

------------------------------------------------------------------------

## Module 1 Quiz!

Q5: In the (hypothetical) 2024 Gallup Happiness Poll, the mean happiness rating is 4 and the standard deviation is 2. Assuming the data are distributed normally, 68% of ratings would be expected to lie between which 2 values?

::: notes
According to the Empirical Rule, in a normal distribution, 68% of values fall within plus or minus 1 SD from the mean. This means that 68% of happiness ratings would fall between 2 and 6.
:::

------------------------------------------------------------------------

## BONUS POINT!

Q6: Which statistics classes or trainings have you taken in the past?

::: notes
free point!
:::

------------------------------------------------------------------------

## Reminders for Next Week!

Don't forget to complete Journal 1 and submit your homework by 12pm on Tuesday (January 21st)!

You can **always** reach out (via Slack, email, office hours) if you have **any** questions!

------------------------------------------------------------------------
